### ISSUE TITLE
flatpak is outdated 1.40.0 --> 1.15.1

### ISSUE THREAD

**Issue by pheiduck** [flathub/org.localsend.localsend_app#52]
This Flatpak is outdated please update.
@Tienisto

**Comment by Tienisto** [comment]
1.15.0 should be available now. Please wait a day or 2 until the flathub bot creates a new PR (I am too lazy to create it myself)

**Comment by pheiduck** [comment]
Yep, it's downloadable now. Thanks to you and the Flathubbot :D ;)
